version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - RULE34_API_KEY=${RULE34_API_KEY}
      - RULE34_USER_ID=${RULE34_USER_ID}
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - backend
